swagger: "2.0"
info: {}
basePath: /open
paths:
  /bizLog/edit:
    get:
      tags:
      - bizLog
  /bizLog/list:
    get:
      tags:
      - bizLog
      description: 获取日志列表
      operationId: BizLogController.Post,Get
      parameters:
      - in: query
        name: page
        description: 页码
        required: true
        type: integer
        format: int64
      - in: query
        name: pageSize
        description: 分页大小
        required: true
        type: integer
        format: int64
      - in: query
        name: moduleName
        description: 模块名称
        type: string
      - in: query
        name: className
        description: 类名称
        type: string
      - in: query
        name: methodName
        description: 方法名称
        type: string
      - in: query
        name: status
        description: 状态
        type: string
      responses:
        "200":
          description: '"0k"'
          schema:
            $ref: '#/definitions/models.BizLog'
        "403":
          description: ': other err'
    post:
      tags:
      - bizLog
      description: 获取日志列表
      operationId: BizLogController.Post,Get
      parameters:
      - in: query
        name: page
        description: 页码
        required: true
        type: integer
        format: int64
      - in: query
        name: pageSize
        description: 分页大小
        required: true
        type: integer
        format: int64
      - in: query
        name: moduleName
        description: 模块名称
        type: string
      - in: query
        name: className
        description: 类名称
        type: string
      - in: query
        name: methodName
        description: 方法名称
        type: string
      - in: query
        name: status
        description: 状态
        type: string
      responses:
        "200":
          description: '"0k"'
          schema:
            $ref: '#/definitions/models.BizLog'
        "403":
          description: ': other err'
  /bizLog/save:
    post:
      tags:
      - bizLog
      description: 获取日志列表
      operationId: BizLogController.Post
      parameters:
      - in: body
        name: body
        description: 日志详情
        required: true
        schema:
          $ref: '#/definitions/models.BizLog'
      responses:
        "200":
          description: '"0k"'
          schema:
            $ref: '#/definitions/models.BizLog'
        "201":
          description: '{int} models.BizLog'
        "403":
          description: ': other err'
  /bizLog/view:
    get:
      tags:
      - bizLog
  /config/view:
    get:
      tags:
      - config
  /config/write:
    post:
      tags:
      - config
  /content/listRemoteFile:
    post:
      tags:
      - content
  /content/queryContent:
    post:
      tags:
      - content
  /content/view:
    get:
      tags:
      - content
  /dataBase/delete:
    post:
      tags:
      - dataBase
      description: delete the ConfigRemote
      operationId: DatabaseController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /dataBase/edit:
    get:
      tags:
      - dataBase
  /dataBase/list:
    get:
      tags:
      - dataBase
    post:
      tags:
      - dataBase
  /dataBase/save:
    post:
      tags:
      - dataBase
  /dataBase/view:
    get:
      tags:
      - dataBase
  /field/:
    get:
      tags:
      - field
      description: get ConfigField
      operationId: FieldController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConfigField'
        "403":
          description: ""
  /field/{id}:
    get:
      tags:
      - field
      description: get ConfigField by id
      operationId: FieldController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConfigField'
        "403":
          description: :id is empty
    put:
      tags:
      - field
      description: update the ConfigField
      operationId: FieldController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for ConfigField content
        required: true
        schema:
          $ref: '#/definitions/models.ConfigField'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConfigField'
        "403":
          description: :id is not int
    delete:
      tags:
      - field
      description: delete the ConfigField
      operationId: FieldController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /field/edit:
    get:
      tags:
      - field
    post:
      tags:
      - field
  /field/save:
    post:
      tags:
      - field
  /help/:
    get:
      tags:
      - help
  /index/:
    get:
      tags:
      - index
  /index/gettime:
    get:
      tags:
      - index
  /index/login:
    get:
      tags:
      - index
    post:
      tags:
      - index
  /index/logout:
    get:
      tags:
      - index
  /index/profile:
    get:
      tags:
      - index
    post:
      tags:
      - index
  /logFile/listRemoteFile:
    post:
      tags:
      - logFile
  /logFile/tailfLog:
    get:
      tags:
      - logFile
  /logFile/view:
    get:
      tags:
      - logFile
  /logFile/viewLog:
    get:
      tags:
      - logFile
  /manager/dataList:
    get:
      tags:
      - manager
    post:
      tags:
      - manager
  /manager/list:
    get:
      tags:
      - manager
  /manager/view:
    get:
      tags:
      - manager
  /monitor/listRemoteFile:
    post:
      tags:
      - monitor
  /monitor/queryContent:
    post:
      tags:
      - monitor
  /monitor/view:
    get:
      tags:
      - monitor
  /remote/delete:
    post:
      tags:
      - remote
      description: delete the ConfigRemote
      operationId: RemoteController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /remote/edit:
    get:
      tags:
      - remote
  /remote/kafkaList:
    post:
      tags:
      - remote
  /remote/list:
    get:
      tags:
      - remote
      description: 获取接口调用历史
      operationId: RemoteController.Get
      parameters:
      - in: query
        name: page
        description: 页码
        required: true
        type: integer
        format: int64
      - in: query
        name: pageSize
        description: 分页大小
        required: true
        type: integer
        format: int64
      - in: query
        name: moduleName
        description: 模块名称
        type: string
      responses:
        "200":
          description: '"0k"'
          schema:
            $ref: '#/definitions/models.BizLog'
        "403":
          description: ': other err'
  /remote/save:
    post:
      tags:
      - remote
  /remote/saveAddr:
    post:
      tags:
      - remote
definitions:
  models.BizLog:
    title: BizLog
    type: object
    properties:
      ClassName:
        description: 类名称
        type: string
      Commemts:
        description: 备注
        type: string
      CreateTime:
        description: 操作时间
        type: string
        format: datetime
      Id:
        description: 日志表id，uuid
        type: string
      Ip:
        description: 操作ip
        type: string
      MethodName:
        description: 方法名称
        type: string
      ModuleName:
        description: 模块名称
        type: string
      Params:
        description: 传入参数
        type: string
      Status:
        type: integer
        format: int64
      UserId:
        description: 用户id,记录操作用户
        type: string
  models.ConfigField:
    title: ConfigField
    type: object
    properties:
      AliasName:
        description: 数据库别名
        type: string
      FieldName:
        description: 字段名称
        type: string
      FieldSort:
        description: 字段排序
        type: integer
        format: int64
      FieldTitle:
        description: 字段标题
        type: string
      FieldType:
        description: 字段类型
        type: string
      Id:
        description: 主键
        type: string
      IsPrimary:
        description: 是否主键
        type: integer
        format: int64
      IsShow:
        description: 是否显示
        type: string
      LogTableName:
        description: 表名称
        type: string
      OrderBy:
        description: 排序（ASC:升序,DESC:降序)
        type: string
      Status:
        description: 状态，0正常 1禁用
        type: integer
        format: int64
tags:
- name: bizLog
  description: |
    查看common日志
- name: field
  description: |
    FieldController operations for ConfigField
- name: remote
  description: |
    RemoteController operations for ConfigRemote
- name: help
  description: |
    HelpController
